/* MUTAGENÊSES v23 — camada online: contas, dados separados e comunidades compartilhadas */
const MG_URL="https://ginilivgbediwlnkjueb.supabase.co";
const MG_KEY="sb_publishable_-69scUrAFvCrOYu_TIjQAQ_lcsscd3s";
let mgSupabase=null,mgCloudTimer=0,mgCloudLoading=false;
appState.auth={ready:false,user:null,mode:"login",message:"",error:""};
function cloudUser(){return appState.auth?.user||null}
function mgLocalPersist(){try{localStorage.setItem(STORE,JSON.stringify({chars:appState.chars,activeId:appState.activeId}));localStorage.setItem(COMMUNITY_STORE,JSON.stringify({communities:appState.communities||[]}));localStorage.setItem('mutageneses-v20-authored',JSON.stringify({customItems:appState.customItems||[],customCapacities:appState.customCapacities||[],threats:appState.threats||[]}));}catch{}}
function mgUuid(){return crypto.randomUUID()}
function ensureCloudIds(){for(const c of appState.chars||[])if(!isUuid(c.id))c.id=mgUuid();for(const x of appState.customItems||[])if(!isUuid(x.id))x.id=mgUuid();for(const x of appState.customCapacities||[])if(!isUuid(x.id))x.id=mgUuid();for(const t of appState.threats||[])if(t.custom&&!isUuid(t.id))t.id=mgUuid();for(const c of appState.communities||[])if(!isUuid(c.id))c.id=mgUuid();}
function mgAuthPage(){const signup=appState.auth.mode==='signup';return `<main class="auth-page"><section class="auth-card terminal"><div class="eyebrow">MUTAGENÊSES // PRIMEIRO ACESSO</div><div class="auth-symbol">☢</div><h1 class="page-title">${signup?'Criar conta':'Entrar'}</h1><p class="muted">Cada jogador possui seus próprios personagens, itens, Capacidades e ameaças. Comunidades conectam contas somente quando você entra ou é convidado.</p>${signup?'<label>Nome de jogador<input id="auth-name" autocomplete="name" placeholder="Como você será visto"></label>':''}<label>E-mail<input id="auth-email" type="email" autocomplete="email" placeholder="voce@exemplo.com"></label><label>Senha<input id="auth-password" type="password" autocomplete="current-password" placeholder="mínimo de 6 caracteres"></label><button class="btn primary" style="width:100%;margin-top:10px" onclick="authSubmit()">${signup?'CRIAR CONTA':'ENTRAR'}</button><button class="btn" style="width:100%;margin-top:8px" onclick="authToggle()">${signup?'Já tenho uma conta':'Criar nova conta'}</button>${appState.auth.error?`<div class="notice warn" style="margin-top:12px">${esc(appState.auth.error)}</div>`:''}${appState.auth.message?`<div class="notice" style="margin-top:12px">${esc(appState.auth.message)}</div>`:''}<p class="muted" style="margin-top:14px;font-size:12px">O conteúdo privado fica separado por conta no banco online. Não compartilhe sua senha.</p></section></main>`}
function authToggle(){appState.auth.mode=appState.auth.mode==='signup'?'login':'signup';appState.auth.error='';appState.auth.message='';render()}
async function authSubmit(){if(!mgSupabase)return;appState.auth.error='';appState.auth.message='';const email=(document.getElementById('auth-email')?.value||'').trim();const password=document.getElementById('auth-password')?.value||'';const name=(document.getElementById('auth-name')?.value||'').trim();if(!email||!password){appState.auth.error='Informe e-mail e senha.';render();return}if(appState.auth.mode==='signup'&&password.length<6){appState.auth.error='A senha precisa ter pelo menos 6 caracteres.';render();return}try{let r;if(appState.auth.mode==='signup')r=await mgSupabase.auth.signUp({email,password,options:{data:{display_name:name||email.split('@')[0]}}});else r=await mgSupabase.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(appState.auth.mode==='signup'&&!r.data.session){appState.auth.message='Conta criada. Confirme seu e-mail (caso a confirmação esteja ativa) e depois entre.';appState.auth.mode='login';render();return}await onCloudLogin(r.data.session)}catch(e){appState.auth.error=e?.message||'Não foi possível autenticar.';render()}}
async function authLogout(){try{await mgSupabase?.auth.signOut()}catch{}clearTimeout(mgCloudTimer);try{localStorage.removeItem(STORE);localStorage.removeItem(COMMUNITY_STORE);localStorage.removeItem('mutageneses-v20-authored')}catch{}appState.auth.user=null;appState.auth.ready=true;appState.chars=[];appState.communities=[];appState.customItems=[];appState.customCapacities=[];appState.threats=defaultThreats();appState.activeId=null;appState.draft=emptyChar();appState.page='home';render()}
async function onCloudLogin(session){appState.auth.user=session?.user||null;appState.auth.ready=true;appState.auth.error='';appState.auth.message='';if(appState.auth.user)await cloudLoad();render()}
function normalizeCloudCommunity(r){return normalizeCommunity({id:r.id,name:r.name,information:r.description||'',resources:r.resources||'',location:r.location||'',reputation:r.reputation||'',membersCount:Number(r.member_count)||0,members:[],joinCode:r.join_code||'',owner_id:r.owner_id})}
async function loadCommunityAccess(uid){const memberships=await mgSupabase.from('community_members').select('community_id,user_id,role,character_id').eq('user_id',uid);if(memberships.error)throw memberships.error;const ids=[...new Set((memberships.data||[]).map(r=>r.community_id))];const owned=await mgSupabase.from('communities').select('*').eq('owner_id',uid);if(owned.error)throw owned.error;const rows=[...(owned.data||[])];const missing=ids.filter(id=>!rows.some(r=>r.id===id));if(missing.length){const joined=await mgSupabase.from('communities').select('*').in('id',missing);if(joined.error)throw joined.error;rows.push(...(joined.data||[]))}const communities=rows.map(normalizeCloudCommunity);if(communities.length){const memberRows=await mgSupabase.from('community_members').select('community_id,user_id,role,character_id').in('community_id',communities.map(c=>c.id));if(memberRows.error)throw memberRows.error;for(const c of communities){const rowsForC=(memberRows.data||[]).filter(m=>m.community_id===c.id);c.members=rowsForC.map(m=>({type:'remote',userId:m.user_id,role:m.role,charId:m.character_id||null}));}}return communities}
async function loadSharedCommunityCharacters(communities){const ids=communities.flatMap(c=>c.members||[]).map(m=>m.charId).filter(Boolean);if(!ids.length)return;const r=await mgSupabase.from('characters').select('*').in('id',[...new Set(ids)]);if(r.error)return;for(const c of communities){for(const m of c.members||[]){if(!m.charId)continue;const row=(r.data||[]).find(x=>x.id===m.charId);if(row)m.char=normalizeChar({...row.data,id:row.id,updatedAt:new Date(row.updated_at||row.created_at).getTime()})}}}
async function cloudLoad(){if(!mgSupabase||!cloudUser()||mgCloudLoading)return;mgCloudLoading=true;try{const uid=cloudUser().id;const [cr,it,ca,th]=await Promise.all([mgSupabase.from('characters').select('*').eq('owner_id',uid),mgSupabase.from('custom_items').select('*').eq('owner_id',uid),mgSupabase.from('custom_capacities').select('*').eq('owner_id',uid),mgSupabase.from('threats').select('*').or(`owner_id.eq.${uid},is_public.eq.true`)]);if(cr.error)throw cr.error;const localBefore=[...appState.chars];const remoteChars=(cr.data||[]).map(r=>normalizeChar({...r.data,id:r.id,updatedAt:new Date(r.updated_at||r.created_at).getTime(),shareToken:r.share_token||r.data?.shareToken||''}));if(remoteChars.length){appState.chars=remoteChars;appState.activeId=remoteChars[0]?.id||null;appState.draft=appState.activeId?clone(active()):emptyChar()}else if(localBefore.length&&!localStorage.getItem('mutageneses-cloud-migrated')){appState.chars=localBefore.map(normalizeChar);ensureCloudIds();await cloudSave();localStorage.setItem('mutageneses-cloud-migrated',uid);localStorage.removeItem(STORE);localStorage.removeItem(COMMUNITY_STORE);localStorage.removeItem('mutageneses-v20-authored')}else{appState.chars=[];appState.activeId=null;appState.draft=emptyChar();appState.customItems=[];appState.customCapacities=[];appState.threats=defaultThreats();appState.communities=[]}if(!it.error&&remoteChars.length)appState.customItems=(it.data||[]).map(r=>({...r.data,id:r.id,custom:true}));else if(!it.error&&localStorage.getItem('mutageneses-cloud-migrated')===uid)appState.customItems=(it.data||[]).map(r=>({...r.data,id:r.id,custom:true}));if(!ca.error)appState.customCapacities=(ca.data||[]).map(r=>({...r.data,id:r.id,custom:true}));if(!ca.error){for(const c of appState.customCapacities)if(!DB.capacities.some(q=>q.id===c.id))DB.capacities.push(c)}if(!th.error){const threats=(th.data||[]).map(r=>normalizeThreat({...r.data,id:r.id,custom:true,is_public:r.is_public,owner_id:r.owner_id}));appState.threats=[...defaultThreats(),...threats]}appState.communities=await loadCommunityAccess(uid);await loadSharedCommunityCharacters(appState.communities);ensureCloudIds();mgLocalPersist()}catch(e){console.error(e);appState.auth.error='Não foi possível carregar todos os dados online. Seus dados locais continuam preservados.'}finally{mgCloudLoading=false}}
async function cloudSave(){if(!mgSupabase||!cloudUser())return;ensureCloudIds();const uid=cloudUser().id;for(const c of appState.chars||[]){const row={id:c.id,owner_id:uid,name:c.meta?.name||'Sem nome',data:c,is_private:Boolean(c.sharing?.private),link_permission:c.sharing?.linkPermission==='edit'?'edit':'view',master_permission:c.sharing?.masterCanEdit?'edit':'view'};const r=await mgSupabase.from('characters').upsert(row,{onConflict:'id'});if(r.error)throw r.error}for(const x of appState.customItems||[]){const r=await mgSupabase.from('custom_items').upsert({id:x.id,owner_id:uid,data:x},{onConflict:'id'});if(r.error)throw r.error}for(const x of appState.customCapacities||[]){const r=await mgSupabase.from('custom_capacities').upsert({id:x.id,owner_id:uid,data:x},{onConflict:'id'});if(r.error)throw r.error}for(const t of (appState.threats||[]).filter(t=>t.custom)){const r=await mgSupabase.from('threats').upsert({id:t.id,owner_id:uid,is_public:Boolean(t.is_public),data:t},{onConflict:'id'});if(r.error)throw r.error}for(const c of appState.communities||[]){const joinCode=c.joinCode||c.join_code;const row={id:c.id,owner_id:uid,name:c.name||'Sem nome',description:c.information||'',location:c.location||'',resources:c.resources||'',reputation:c.reputation||'',member_count:Number(c.membersCount)||0};if(joinCode)row.join_code=joinCode;const r=await mgSupabase.from('communities').upsert(row,{onConflict:'id'});if(r.error)throw r.error;const ownerLink=await mgSupabase.from('community_members').upsert({community_id:c.id,user_id:uid,role:'owner',character_id:null},{onConflict:'community_id,user_id'});if(ownerLink.error)console.warn(ownerLink.error)}mgLocalPersist()}
function queueCloudSave(){if(!mgSupabase||!cloudUser())return;clearTimeout(mgCloudTimer);mgCloudTimer=setTimeout(()=>cloudSave().catch(e=>console.error(e)),600)}
function communityJoinCode(){return Math.random().toString(36).slice(2,10).toUpperCase()}
async function joinCommunityByCode(){const code=(prompt('Digite o código da comunidade:')||'').trim().toLowerCase();if(!code||!mgSupabase||!cloudUser())return;try{const r=await mgSupabase.rpc('join_community',{p_join_code:code});if(r.error)throw r.error;await cloudLoad();const joinedId=r.data?.id||r.data?.[0]?.id;if(joinedId){appState.communityId=joinedId;appState.page='communities'}render();toastCloud('Você entrou na comunidade.')}catch(e){alert(e?.message||'Não foi possível entrar na comunidade.')}}
function linkCharacterCloud(communityId,charId){const uid=cloudUser()?.id;if(!uid||!mgSupabase)return;const c=(appState.communities||[]).find(c=>c.id===communityId);if(!c)return;mgSupabase.from('community_members').upsert({community_id:communityId,user_id:uid,role:c.owner_id===uid?'owner':'member',character_id:charId||null},{onConflict:'community_id,user_id'}).then(({error})=>{if(error)console.error(error);else{mgSupabase.from('shared_characters').delete().eq('character_id',charId).eq('community_id',communityId).then(()=>mgSupabase.from('shared_characters').insert({character_id:charId,community_id:communityId,permission:'view'})).then(()=>{});const m=c.members.find(m=>m.userId===uid);if(m)m.charId=charId;else c.members.push({type:'remote',userId:uid,role:'member',charId});persistCommunities();render();}})}
function toastCloud(text){let t=document.getElementById('mg-toast');if(!t){t=document.createElement('div');t.id='mg-toast';t.className='toast';document.body.appendChild(t)}t.textContent=text;t.style.display='block';clearTimeout(t._timer);t._timer=setTimeout(()=>t.style.display='none',3200)}
const __persistCloud=persist;persist=function(){__persistCloud();queueCloudSave()};
const __persistCommunitiesCloud=persistCommunities;persistCommunities=function(){__persistCommunitiesCloud();queueCloudSave()};
const __createCommunityLocal=createCommunity;createCommunity=function(){__createCommunityLocal();const c=appState.communities.find(c=>c.id===appState.communityId);if(c&&!c.joinCode)c.joinCode=communityJoinCode();persistCommunities();render()};
const __addLocalToCommunity=addLocalToCommunity;addLocalToCommunity=function(id,charId){__addLocalToCommunity(id,charId);linkCharacterCloud(id,charId)};
const __removeCommunityMember=removeCommunityMember;removeCommunityMember=function(id,index){const c=appState.communities.find(c=>c.id===id);const m=c?.members?.[index];if(m?.type==='remote'&&cloudUser()){mgSupabase.from('community_members').delete().eq('community_id',id).eq('user_id',cloudUser().id).then(()=>{if(m.charId)mgSupabase.from('shared_characters').delete().eq('community_id',id).eq('character_id',m.charId).then(()=>{})})}__removeCommunityMember(id,index)};
const __selectCharacterCloud=selectCharacter;selectCharacter=function(id){__selectCharacterCloud(id);queueCloudSave()};
const __deleteCharacterCloud=deleteCharacter;deleteCharacter=function(id){__deleteCharacterCloud(id);queueCloudSave()};
const __saveThreatFormCloud=saveThreatForm;saveThreatForm=function(){__saveThreatFormCloud();queueCloudSave()};
const __createCustomItemCloud=createCustomItem;createCustomItem=function(){__createCustomItemCloud();queueCloudSave()};
const __createCustomCapabilityCloud=createCustomCapability;createCustomCapability=function(){__createCustomCapabilityCloud();queueCloudSave()};
const __setShareSettingCloud=setShareSetting;setShareSetting=function(a,b){__setShareSettingCloud(a,b);queueCloudSave()};
const __communitiesCloud=communities;communities=function(){let html=__communitiesCloud();const selected=appState.communities.find(c=>c.id===appState.communityId)||appState.communities[0];if(selected){const code=selected.joinCode||'GERANDO';const codeCall=JSON.stringify(code);html=html.replace('<section class="community-editor">',`<section class="community-editor"><div class="terminal section"><div class="section-head"><div><div class="label">ACESSO DA COMUNIDADE</div><p class="muted" style="margin:4px 0 0">Compartilhe este código somente com quem você deseja convidar.</p></div><div class="actions"><span class="tag acid">CÓDIGO ${esc(code)}</span><button class="btn" onclick="copyText(${codeCall})">Copiar código</button></div></div></div>`);}return html};
const __shellCloud=shell;shell=function(content){__shellCloud(content);const header=document.querySelector('.top-inner');if(header&&!document.getElementById('accountBar')){const bar=document.createElement('div');bar.id='accountBar';bar.className='account-bar';bar.innerHTML=`<span>${esc(cloudUser()?.user_metadata?.display_name||cloudUser()?.email||'Jogador')}</span><button class="btn" onclick="joinCommunityByCode()">Entrar em comunidade</button><button class="btn ghost" onclick="authLogout()">Sair</button>`;header.appendChild(bar)}};
function onlineRender(){if(!appState.auth?.ready){document.getElementById('app').innerHTML='<main class="auth-page"><section class="auth-card terminal"><div class="eyebrow">MUTAGENÊSES // INICIALIZAÇÃO</div><h1 class="page-title">CARREGANDO...</h1><p class="muted">Conectando ao terminal do sobrevivente.</p></section></main>';return}if(!cloudUser()){document.getElementById('app').innerHTML=mgAuthPage();return}renderBase()}
const renderBase=render;render=onlineRender;
async function cloudInit(){try{if(!window.supabase?.createClient)throw new Error('Biblioteca Supabase não carregou.');mgSupabase=window.supabase.createClient(MG_URL,MG_KEY);const {data}=await mgSupabase.auth.getSession();if(data?.session)await onCloudLogin(data.session);else{appState.auth.ready=true;render()}mgSupabase.auth.onAuthStateChange((_event,session)=>setTimeout(()=>{if(session?.user)onCloudLogin(session);else if(appState.auth.user)authLogout()},0))}catch(e){appState.auth.ready=true;appState.auth.error='Falha ao iniciar o acesso online: '+(e?.message||'erro desconhecido');render()}}
cloudInit();